DROP DATABASE IF EXISTS RentaFriendDB;
CREATE DATABASE RentaFriendDB;
USE RentaFriendDB;

CREATE TABLE friend (
    friend_id TINYINT UNSIGNED AUTO_INCREMENT,
    friend VARCHAR(30) NOT NULL,
    age CHAR(2) NOT NULL,
    adjectives VARCHAR(20) NOT NULL,
    imgurl VARCHAR(30) NOT NULL,
    price DECIMAL(4,2) NOT NULL,
    interests VARCHAR(50) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_friends PRIMARY KEY (friend_id)
);



CREATE TABLE USER (
    user_id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL,
    fName VARCHAR(30) NOT NULL,
    lName VARCHAR(30) NOT NULL,
    email VARCHAR (30) NOT NULL UNIQUE,
    password VARCHAR (30) NOT NULL UNIQUE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_id PRIMARY KEY (user_id)
);
